version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(frontend)"
      prefix-development: "chore(frontend-dev)"
      include: "scope"
    groups:
      core-dependencies:
        patterns:
          # Reactとそのエコシステム
          - "next"
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
          - "@tanstack/react-query"
          - "typescript"
          - "@types/node"
          # Cloudflareデプロイメント関連
          - "wrangler"
          - "@opennextjs/cloudflare"
          - "@cloudflare/workers-types"
          # スタイリング関連
          - "tailwindcss"
          - "@tailwindcss/postcss"
          - "postcss"
          - "postcss-load-config"
      dev-tools:
        patterns:
          # 開発ツール関連
          - "@biomejs/biome"
          - "knip"

  # apiディレクトリの依存関係を管理
  - package-ecosystem: "bun"
    directory: "/api"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(api)"
      prefix-development: "chore(api-dev)"
      include: "scope"
    # ここで特定パッケージをグルーピング
    groups:
      core-dependencies:
        patterns:
          # コアとなる実行時依存パッケージ
          - "hono"
          - "drizzle-orm"
          - "dotenv"
          - "typescript"
          - "@types/node"
          # Cloudflare関連のデプロイメント
          - "wrangler"
          - "@cloudflare/workers-types"
          # データベース関連ツール
          - "drizzle-kit"
      testing-frameworks:
        patterns:
          # テスト関連パッケージ
          - "vitest"
          - "@vitest/coverage-v8"
          - "happy-dom"
      code-quality:
        patterns:
          # コード品質管理ツール
          - "@biomejs/biome"
          - "knip"

  # Extensionディレクトリの依存関係を管理
  - package-ecosystem: "bun"
    directory: "/extension"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(extension)"
      prefix-development: "chore(extension-dev)"
      include: "scope"
    # ここで特定パッケージをグルーピング
    groups:
      devdependencies:
        patterns:
          - "@biomejs/biome"
          - "@types/node"
          - "knip"
          - "typescript"

  # GitHub Actionsの依存関係を管理
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(actions)"
      prefix-development: "chore(actions)"
      include: "scope"
