version: 2
updates:
  # frontendディレクトリの依存関係を管理
  - package-ecosystem: "bun"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(frontend)"
      prefix-development: "chore(frontend)"
      include: "scope"
    # ここで特定パッケージをグルーピング
    groups:
      next-react-deployment:
        patterns:
          # 依存パッケージ名ベースでの指定
          - "next"
          - "react"
          - "react-dom"
          - "wrangler"
          - "@opennextjs/cloudflare"
          - "@cloudflare/workers-types"
          - "@types/node"
          - "@types/react"
          - "@types/react-dom"
      styles:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/postcss"
          - "postcss"
          - "postcss-load-config"

  # apiディレクトリの依存関係を管理
  - package-ecosystem: "bun"
    directory: "/api"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(api)"
      prefix-development: "chore(api)"
      include: "scope"
    groups:
      core-dependencies:
        patterns:
          - "hono"
          - "drizzle-orm"
          - "dotenv"
          - "wrangler"
          - "@cloudflare/workers-types"
          - "drizzle-kit"
          - "typescript"
          - "@types/node"
      testing-frameworks:
        patterns:
          # テスト関連パッケージ
          - "vitest"
          - "@vitest/coverage-v8"
          - "happy-dom"
      code-quality:
        patterns:
          # コード品質管理ツール
          - "@biomejs/biome"
          - "knip"

  # Extensionディレクトリの依存関係を管理
  - package-ecosystem: "bun"
    directory: "/extension"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(extension)"
      prefix-development: "chore(extension)"
      include: "scope"
    # ここで特定パッケージをグルーピング
    groups:
      devdependencies:
        patterns:
          - "@biomejs/biome"
          - "@types/node"
          - "knip"
          - "typescript"

  # GitHub Actionsの依存関係を管理
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
