name: API Lint

on:
  pull_request:
    paths:
      - 'api/**'
      - '.github/workflows/api-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@99663b1e4fb6a8f8bd9dd78a899d3969d7ca7573 # v4.2.1
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run Knip    
        run: npm run knip
