name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    name: Build Checks
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@v4
        with:
          node-version: 20
    
      - name: API Install dependencies
        run: npm ci
        working-directory: ./api
        
      - name: API Type check
        run: npx tsc --noEmit
        working-directory: ./api

      - name: Frontend Install dependencies
        run: npm ci
        working-directory: ./frontend
        
      - name: Frontend Lint
        run: npm run lint
        working-directory: ./frontend
        
      - name: Frontend Type check
        run: npx tsc --noEmit
        working-directory: ./frontend
        
  deploy:
    needs: checks
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@v4
        with:
          node-version: 20
    
      - name: API Install dependencies
        run: npm ci
        working-directory: ./api

      - name: Frontend Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Deploy API
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./api
          packageManager: npm

      - name: Deploy Frontend
        run: npm run deploy
        working-directory: ./frontend
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
