name: Extension Lint

on:
  pull_request:
    paths:
      - 'extension/**'
      - '.github/workflows/extension-lint.yml'

jobs:
  lint:
    runs-on: self-hosted
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./extension

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun lint
