name: Extension Lint

on:
  pull_request:
    paths:
      - 'extension/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./extension

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
            bun-version: 1.2.8

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun lint

      - name: Run Knip
        run: bun knip
