name: extension-knip

on:
  pull_request:
    paths:
      - 'extension/**'

jobs:
  knip:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    defaults:
      run:
        working-directory: ./extension
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './extension/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run Knip
        id: knip-check
        run: npm run knip