name: Extension Lint

on:
  pull_request:
    paths:
      - 'extension/**'
      - '.github/workflows/extension-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./extension

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
            bun-version: 1.2.8

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun lint

      - name: Run Knip
        run: bun knip
