name: Frontend Checks

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-lint.yml'

permissions:
  pull-requests: write
  contents: read

jobs:
  checks:
    runs-on: self-hosted
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
        
      - name: Run typecheck
        run: npx tsc --noEmit

      - name: Run tests with coverage
        id: test
        run: npm run test:coverage

      - name: Extract coverage
        id: coverage
        run: |
          COVERAGE=$(cat coverage/coverage-summary.json | jq -r '.total.statements.pct')
          COVERAGE_DETAIL=$(cat coverage/coverage-summary.json | jq -r '
            "### カバレッジ詳細\n" +
            "| Type | Percentage | \n" +
            "|------|------------|\n" +
            "| Statements | \(.total.statements.pct)% |\n" +
            "| Branches | \(.total.branches.pct)% |\n" +
            "| Functions | \(.total.functions.pct)% |\n" +
            "| Lines | \(.total.lines.pct)% |"
          ')
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "detail<<EOF" >> $GITHUB_OUTPUT
          echo "$COVERAGE_DETAIL" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # TODO: カバレッジが8割を超えるまで一時的に無効化
      # - name: Check coverage threshold
      #   run: |
      #     COVERAGE=${{ steps.coverage.outputs.coverage }}
      #     echo "Checking if coverage ($COVERAGE%) meets threshold (80%)..."
      #     if [ "$(echo "$COVERAGE < 80" | bc -l)" -eq 1 ]; then
      #       echo "❌ Coverage ($COVERAGE%) is below threshold (80%)"
      #       exit 1
      #     else
      #       echo "✅ Coverage ($COVERAGE%) meets or exceeds threshold (80%)"
      #     fi

      - name: Post coverage comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: frontend-test-coverage
          message: |
            ### フロントエンドテストカバレッジレポート

            フロントエンド全体のカバレッジ: ${{ steps.coverage.outputs.coverage }}%
            必要なカバレッジ閾値: 80% (現在は無効化中)

            ${{ steps.coverage.outputs.detail }}

            判定: ✅ カバレッジチェック無効化中（8割到達まで）

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report-${{ github.run_number }}
          path: frontend/coverage/
          retention-days: 7
          if-no-files-found: warn