name: frontend-knip

on:
  pull_request:
    paths:
      - 'frontend/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  knip:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run Knip
        id: knip-check
        run: npm run knip