name: Frontend Checks

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-lint.yml'

jobs:
  checks:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
        
      - name: Run typecheck
        run: npx tsc --noEmit
