name: Frontend Tests

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main
  pull_request:
    paths:
      - 'frontend/**'

permissions:
  pull-requests: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        id: test
        run: npm run test:coverage

      - name: Extract coverage
        id: coverage
        run: |
          COVERAGE=$(cat coverage/coverage-summary.json | jq -r '.total.statements.pct')
          COVERAGE_DETAIL=$(cat coverage/coverage-summary.json | jq -r '
            "### カバレッジ詳細\n" +
            "| Type | Percentage | \n" +
            "|------|------------|\n" +
            "| Statements | \(.total.statements.pct)% |\n" +
            "| Branches | \(.total.branches.pct)% |\n" +
            "| Functions | \(.total.functions.pct)% |\n" +
            "| Lines | \(.total.lines.pct)% |"
          ')
          echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
          echo "detail<<EOF" >> $GITHUB_OUTPUT
          echo "$COVERAGE_DETAIL" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check coverage threshold
        run: |
          COVERAGE=${{ steps.coverage.outputs.coverage }}
          if (( $(echo "$COVERAGE < 65" | bc -l) )); then
            echo "Coverage ($COVERAGE%) is below threshold (65%)"
            exit 1
          fi

      - name: Post coverage comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: frontend-test-coverage
          message: |
            ### フロントエンドテストカバレッジレポート

            カバレッジ: ${{ steps.coverage.outputs.coverage }}%
            閾値: 80%

            ${{ steps.coverage.outputs.detail }}

            ステータス: ${{ steps.coverage.outputs.coverage >= 80 && '✅ Pass' || '❌ Fail' }}

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: frontend/coverage/
          retention-days: 7