name: frontend-knip

on:
  pull_request:
    paths:
      - 'frontend/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: '22'
          # NPM キャッシュを有効にする
          cache: 'npm'

      # 追加のキャッシュ（node_modules）を利用する場合の例
      - name: node modules cache
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: './node_modules'
          key: ${{ runner.os }}-build-${{ hashFiles('.node-version') }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        # 上のキャッシュがヒットしなかった場合にのみインストール実行
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Knip
        id: knip-check
        # knip の実行結果を /tmp/knip-report へリダイレクト
        # continue-on-error: true は「Knip で検知があってもジョブを fail させない」設定
        run: npm run knip > /tmp/knip-report
        continue-on-error: true

      - name: Create PR comment
        uses: actions/github-script@v6
        if: steps.knip-check.outcome == 'failure'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs')
            const knipReport = fs.readFileSync('/tmp/knip-report', 'utf8')

            // コメント本文
            const output = `
            ## フロントエンド Knip レポート
            
            <details>
              <summary>詳細レポート 📖</summary>
              
              \`\`\`
              ${knipReport}
              \`\`\`
              
            </details>
            `

            // Pull Request にコメントを投稿
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
