name: MCP Lint

on:
  pull_request:
    paths:
      - 'mcp/**'
      - '.github/workflows/mcp-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mcp

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
        
      - name: Type check
        run: npm run typecheck